- name: add user
  ansible.builtin.user:
  name: roboshop

- name: removing old app content
  ansible.builtin.file:
    path: /app
    state: absent

- name: creating app directory
  ansible.builtin.file:
    path: /app
    state: directory

- name: downloading {{component}} app content
  ansible.builtin.unarchive:
    src: curl -o /tmp/catalogue.zip https://roboshop-artifacts.s3.amazonaws.com/{{component}}.zip
    dest: /app





