- name: install python3.6
  ansible.builtin.yum:
    name:
      - python36
      - gcc
      - python-devel
    state: installed

- name: app pre-req
  ansible.builtin.include_tasks: "app-prereq.yml"

- name: download python dependencies
  ansible.builtin.pip:
    requirements: /app/requirements.txt
    executable: pip3.6

- name: systemd setup
  ansible.builtin.iclude_tasks: "systemd.yml"

